version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: vetlanh_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vetlanh}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vetlanh_password}
      POSTGRES_DB: ${POSTGRES_DB:-vetlanh_db}
      ADMIN_USERS: duy1
    ports:
      - "5432:5432"
    volumes:
      - vetlanh_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-vetlanh} -d ${POSTGRES_DB:-vetlanh_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  vetlanh_postgres_data:
