"""add_bill_image_path_to_subscriptions

Revision ID: 0179de7757ca
Revises: c07571f977b0
Create Date: 2026-06-10 16:22:40.830210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0179de7757ca'
down_revision: Union[str, Sequence[str], None] = 'c07571f977b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('bill_image_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'bill_image_path')
    # ### end Alembic commands ###
