"""add_goals_to_users

Revision ID: 22b8162d9ddc
Revises: 77f9ff98101d
Create Date: 2026-05-31 16:28:39.056414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22b8162d9ddc'
down_revision: Union[str, Sequence[str], None] = '77f9ff98101d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('goals', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goals')
    # ### end Alembic commands ###
