"""add_user_safety_plans

Revision ID: a614479bf5b7
Revises: 5bd7b1e081c8
Create Date: 2026-06-02 13:23:09.988395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a614479bf5b7'
down_revision: Union[str, Sequence[str], None] = '5bd7b1e081c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_safety_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warning_signs', postgresql.ARRAY(sa.String(length=255)), server_default='{}', nullable=False),
    sa.Column('coping_activities', postgresql.ARRAY(sa.String(length=255)), server_default='{}', nullable=False),
    sa.Column('trusted_contacts', postgresql.ARRAY(sa.String(length=512)), server_default='{}', nullable=False),
    sa.Column('reasons_to_live', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_safety_plans_user_id'), 'user_safety_plans', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_safety_plans_user_id'), table_name='user_safety_plans')
    op.drop_table('user_safety_plans')
    # ### end Alembic commands ###
